# Generated by Django 6.0.5 on 2026-06-08 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
        ('swap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storage_variant',
            field=models.OneToOneField(blank=True, help_text="Link to the swap catalog variant whose uk_end_user_price_ngn drives this product's price. Leave blank for non-iPhone products.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_product', to='swap.storagevariant'),
        ),
    ]
