# Generated by Django 6.0.5 on 2026-06-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=False, help_text="Hidden products won't appear on the store even if in stock."),
        ),
    ]
