# Generated by Django 6.0.5 on 2026-09-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to a video of this exact unit — e.g. a post on X, Instagram, or TikTok.', max_length=500),
        ),
    ]
