# Generated by Django 6.0.5 on 2026-06-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Foreign Used', 'Foreign Used'), ('Nigeria-Used', 'Nigeria-Used')], default='Foreign Used', max_length=20),
        ),
    ]
