# Generated by Django 6.0.5 on 2026-06-20 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagevariant',
            options={'ordering': ['model__name', 'capacity']},
        ),
        migrations.AddField(
            model_name='storagevariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagevariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
