# Generated by Django 6.0.5 on 2026-08-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('bio', models.TextField()),
                ('credentials', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, upload_to='authors/')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('release_year', models.PositiveIntegerField()),
                ('chipset', models.CharField(max_length=100)),
                ('ram_options', models.JSONField(default=list)),
                ('storage_options', models.JSONField(default=list)),
                ('display_specs', models.JSONField(default=dict)),
                ('camera_specs', models.JSONField(default=dict)),
                ('battery_capacity_mah', models.PositiveIntegerField(blank=True, null=True)),
                ('price_band_ngn', models.CharField(blank=True, max_length=50)),
                ('price_band_cad', models.CharField(blank=True, max_length=50)),
                ('conditions_available', models.JSONField(default=list)),
                ('pros', models.JSONField(default=list)),
                ('cons', models.JSONField(default=list)),
                ('verdict_summary', models.TextField(blank=True, help_text='1–2 sentence direct verdict. Lead with the answer — AI engines lift this near-verbatim.')),
                ('hero_image', models.ImageField(blank=True, upload_to='devices/')),
                ('is_in_stock', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='UseCaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BuyingGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('intro', models.TextField(help_text='Open with a direct verdict/summary of who this guide is for.')),
                ('body', models.TextField(blank=True, help_text='Optional supplementary prose.')),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.author')),
                ('use_case_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.usecasetag')),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Must match natural search phrasing, e.g. 'galaxy-s24-vs-s24-ultra'.", unique=True)),
                ('intro', models.TextField(help_text='Open with a direct 1–2 sentence verdict, not scene-setting.')),
                ('winner_by_category', models.JSONField(default=dict, help_text='{"camera": "a", "battery": "b", "display": "a", "value": "b", "performance": "a"}')),
                ('overall_recommendation', models.TextField(help_text='Use if/then phrasing: "If you shoot video → A. If you want better value → B."')),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.author')),
                ('device_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_a', to='content.device')),
                ('device_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_b', to='content.device')),
            ],
        ),
        migrations.CreateModel(
            name='FAQBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='use_case_tags',
            field=models.ManyToManyField(blank=True, to='content.usecasetag'),
        ),
        migrations.CreateModel(
            name='BuyingGuideEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('blurb', models.TextField(help_text='Why THIS device for THIS persona. Use if/then: "If you need the best camera → this one."')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='content.buyingguide')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.device')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('guide', 'rank')},
            },
        ),
    ]
