# Generated by Django 6.0.5 on 2026-08-17 14:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyingguide',
            options={'ordering': ['-published_at', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='comparison',
            options={'ordering': ['-published_at', '-updated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='buyingguideentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='buyingguide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comparison',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='form_factor',
            field=models.CharField(choices=[('phone', 'Phone'), ('laptop', 'Laptop')], default='phone', help_text='Physical device category. Not a use-case — drives filtering, not persona guides.', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Controls the /phones/<slug> meta description. Falls back to verdict_summary if blank.', max_length=160),
        ),
        migrations.AlterField(
            model_name='buyingguide',
            name='use_case_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.usecasetag'),
        ),
        migrations.AlterField(
            model_name='buyingguideentry',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.device'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='device_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons_as_a', to='content.device'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='device_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons_as_b', to='content.device'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='winner_by_category',
            field=models.JSONField(default=dict, help_text='{"camera": "a", "battery": "b", "display": "a", "value": "b", "performance": "a"}. Values: a / b / tie.'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_in_stock',
            field=models.BooleanField(default=True, help_text='Human-facing stock hint only. NOT wired to the live catalog yet, so it is deliberately excluded from Product structured data until it is.'),
        ),
        migrations.AddIndex(
            model_name='faqblock',
            index=models.Index(fields=['content_type', 'object_id'], name='content_faq_content_611cc1_idx'),
        ),
        migrations.AddConstraint(
            model_name='buyingguideentry',
            constraint=models.UniqueConstraint(fields=('guide', 'rank'), name='unique_guide_rank'),
        ),
        migrations.AddConstraint(
            model_name='buyingguideentry',
            constraint=models.UniqueConstraint(fields=('guide', 'device'), name='unique_guide_device'),
        ),
        migrations.AddConstraint(
            model_name='comparison',
            constraint=models.UniqueConstraint(fields=('device_a', 'device_b'), name='unique_comparison_pair'),
        ),
        migrations.AddConstraint(
            model_name='faqblock',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'question'), name='unique_faq_per_object'),
        ),
    ]
