# Generated by Django 6.0.5 on 2026-08-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_buyingguide_options_alter_comparison_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='battery_wh',
            field=models.PositiveIntegerField(blank=True, help_text='Laptop battery in watt-hours. Leave blank for phones (use mAh).', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='battery_capacity_mah',
            field=models.PositiveIntegerField(blank=True, help_text='Phone battery in mAh. Leave blank for laptops (use battery_wh).', null=True),
        ),
    ]
